# Generated by Django 5.0.6 on 2024-07-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0004_livro_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='capa',
            field=models.ImageField(blank=True, upload_to='media/capas/%d/%m/%Y'),
        ),
    ]
